services:
  # IAM Service
  - type: web
    name: iam-service
    env: node
    buildCommand: cd backend/iam-service && npm install && npm run build
    startCommand: cd backend/iam-service && npm run start:prod
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        value: ./iam_db.sqlite
    plan: free

  # Patient Service
  - type: web
    name: patient-service
    env: node
    buildCommand: cd backend/patient-service && npm install && npm run build
    startCommand: cd backend/patient-service && npm run start:prod
    envVars:
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        value: ./patient_db.sqlite
    plan: free
