version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    networks:
      - internal-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal-net

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal-net

  mlflow:
    image: bitnami/mlflow:2
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
    volumes:
      - mlflow_data:/bitnami/mlflow
    networks:
      - internal-net

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    networks:
      - internal-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - internal-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - internal-net
    depends_on:
      - prometheus

  # ----------------------------------------------------
  # Microservices
  # ----------------------------------------------------


  iam-service:
    build: ./iam-service
    networks:
      - internal-net
    depends_on:
      postgres:
        condition: service_healthy

  patient-service:
    build: ./patient-service
    networks:
      - internal-net
    depends_on:
      postgres:
        condition: service_healthy


  ai-cds-service:
    build: ./ai-cds-service
    networks:
      - internal-net
    depends_on:
      - mlflow
      - chromadb
      - rabbitmq


  interop-gateway:
    build: ./interop-gateway
    networks:
      - internal-net



volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  mlflow_data:
  chromadb_data:
  prometheus_data:
  grafana_data:

networks:
  external-net:
  internal-net:
