import { IAM_SERVICE_URL, PATIENT_SERVICE_URL } from '../config';
export const IAM_SERVICE_URL = process.env.NEXT_PUBLIC_IAM_SERVICE_URL || `${IAM_SERVICE_URL}';
export const PATIENT_SERVICE_URL = process.env.NEXT_PUBLIC_PATIENT_SERVICE_URL || `${PATIENT_SERVICE_URL}';
